import type { Nuxt } from '@nuxt/schema'

import type { ShopifyConfig } from '../types'

import { relative, sep } from 'node:path'

import { addTemplate } from '@nuxt/kit'
import { kebabCase } from 'scule'

import { ShopifyClientType } from '../schemas'
import { getConfiguredClients } from '../utils/clients'

const PROJECT_ORDER = [
  ShopifyClientType.Admin,
  ShopifyClientType.CustomerAccount,
  ShopifyClientType.Storefront,
]

const DIR_IGNORES = ['node_modules', 'dist', '.nuxt', '.output']

const toPosix = (path: string) => path.split(sep).join('/')

interface GraphqlProject {
  schema: string
  documents: string[]
  exclude: string[]
}

function splitDocuments(documents: string[]): Pick<GraphqlProject, 'documents' | 'exclude'> {
  const include: string[] = []
  const exclude: string[] = []

  for (const entry of documents) {
    if (!entry.startsWith('!')) {
      include.push(entry)
      continue
    }

    const glob = entry.slice(1)
    exclude.push(DIR_IGNORES.includes(glob) ? `**/${glob}/**` : glob)
  }

  for (const dir of DIR_IGNORES) {
    exclude.push(`**/${dir}/**`)
  }
  exclude.push('**/*.d.ts')

  return {
    documents: [...new Set(include)],
    exclude: [...new Set(exclude)],
  }
}

export default async function setupGraphqlConfig(nuxt: Nuxt, config: ShopifyConfig) {
  if (!config.graphql.generateConfig) return

  const configured = getConfiguredClients(config)
  const buildDir = toPosix(relative(nuxt.options.rootDir, nuxt.options.buildDir)) || '.nuxt'

  const projects: Record<string, GraphqlProject> = {}

  for (const clientType of PROJECT_ORDER) {
    if (!configured.includes(clientType)) continue

    const clientConfig = config.clients[clientType]

    if (!clientConfig || clientConfig.codegen?.skip) continue

    const name = clientType === ShopifyClientType.Storefront ? 'default' : clientType

    projects[name] = {
      schema: `${buildDir}/schema/${kebabCase(clientType)}.schema.json`,
      ...splitDocuments(clientConfig.documents ?? []),
    }
  }

  if (!Object.keys(projects).length) return

  addTemplate({
    filename: 'graphql.config.mjs',
    write: true,
    getContents: () =>
      '// Generated by @nuxtjs/shopify\n'
      + `export const projects = ${JSON.stringify(projects, null, 2)}\n\n`
      + 'export default { projects }\n',
  })
}
