export const icons = {
    cart: 'hugeicons:shopping-bag-01',
    cartAdd: 'hugeicons:shopping-bag-add',
    cartRemove: 'hugeicons:shopping-bag-remove',
    account: 'hugeicons:user-account',
    sortAsc: 'hugeicons:sort-by-up-02',
    sortDesc: 'hugeicons:sort-by-down-02',
    sort: 'hugeicons:sorting-05',
    filter: 'hugeicons:filter-horizontal',
    sun: 'hugeicons:sun-02',
    moon: 'hugeicons:moon-02',
    menu: 'hugeicons:menu-01',
    globe: 'hugeicons:globe-02',
    close: 'hugeicons:cancel-01',
    github: 'hugeicons:github-01',
}
