name: "Compatibility"

env:
  NUXT_SHOPIFY_NAME: ${{ secrets.NUXT_SHOPIFY_NAME }}

  NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN }}

  NUXT_SHOPIFY_CLIENTS_ADMIN_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_ADMIN_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_ADMIN_CLIENT_ID: ${{ secrets.NUXT_SHOPIFY_CLIENTS_ADMIN_CLIENT_ID }}
  NUXT_SHOPIFY_CLIENTS_ADMIN_CLIENT_SECRET: ${{ secrets.NUXT_SHOPIFY_CLIENTS_ADMIN_CLIENT_SECRET }}

  NUXT_SHOPIFY_CLIENTS_CUSTOMER_ACCOUNT_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_CUSTOMER_ACCOUNT_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_CUSTOMER_ACCOUNT_CLIENT_ID: ${{ secrets.NUXT_SHOPIFY_CLIENTS_CUSTOMER_ACCOUNT_CLIENT_ID }}
  NUXT_SHOPIFY_CLIENTS_CUSTOMER_ACCOUNT_SESSION_PASSWORD: ${{ secrets.NUXT_SHOPIFY_CLIENTS_CUSTOMER_ACCOUNT_SESSION_PASSWORD }}

on:
  schedule:
    - cron: "0 4 * * 1"

  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  node:
    name: "node ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.19.0, 24.11.0]
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v6.0.10
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run tests
        run: pnpm run prepare && pnpm run prepare:playgrounds && pnpm run test

  hydrogen:
    name: "hydrogen ${{ matrix.hydrogen }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hydrogen: ["2024", "2026"]
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v6.0.10
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.20.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Pin the hydrogen peers
        run: pnpm add -D -w "@shopify/hydrogen@${{ matrix.hydrogen }}" "@shopify/hydrogen-react@${{ matrix.hydrogen }}"

      - name: Run tests
        run: pnpm run prepare && pnpm run prepare:playgrounds && pnpm run test
