name: "Dependencies"

on:
  pull_request:
  merge_group:

  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check provenance downgrades
        uses: danielroe/provenance-action@v0.2.0
        with:
          fail-on-provenance-change: false

      - name: Dependency review
        uses: actions/dependency-review-action@v5.0.0
        with:
          base-ref: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha || github.event.before }}
          head-ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha || github.event.after }}
